name: Build & Deploy Android app

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    name: Build & deploy Android release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          cache: gradle
          distribution: temurin

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: echo '${{ secrets.KEYSTORE_FILE }}' | base64 --decode > '${{ github.workspace }}/key.jks'

      - name: Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/key.properties
        run: |
          echo 'storeFile=${{ github.workspace }}/key.jks' > $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH

      - name: Create Release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: app-release.apk
          path: ./app/build/outputs/apk/release/app-release.apk

      - name: Get version code
        id: version
        run: echo "VERSION_CODE=$(grep 'versionCode' ./app/build.gradle.kts | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --verify-tag \
            --title "${{ github.ref_name }}" \
            --generate-notes \
            --notes-file fastlane/metadata/android/en-US/changelogs/${{ steps.version.outputs.VERSION_CODE }}.txt \
            ./app/build/outputs/apk/release/app-release.apk
        env:
          GH_TOKEN: ${{ github.token }}
