name: Build & Deploy Android app

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    name: Build & deploy Android release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          cache: gradle
          distribution: temurin

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: echo '${{ secrets.KEYSTORE_FILE }}' | base64 --decode > '${{ github.workspace }}/key.jks'

      - name: Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/key.properties
        run: |
          echo 'storeFile=${{ github.workspace }}/key.jks' > $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH

      - name: Create Release APK
        run: ./gradlew assembleRelease

      - name: Get latest tag
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release.apk
          path: ./app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        run: |
          gh release create "$TAG" \
            --verify-tag \
            --title "$TAG" \
            --generate-notes \
            ./app/build/outputs/apk/release/app-release.apk
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
